#!/usr/bin/env node
//require('coffee-script');

var opts = {}, key;
process.argv.forEach(function(val, idx) {
  if ( /^\-+/.test(val) ) {
    key = val.replace(/^\-+/, '')
    if ( !process.argv[ idx + 1 ]
        || /^\-+/.test(process.argv[ idx + 1 ]) ) {
      opts[ key ] = true
    } else {
      opts[ key ] = process.argv[ ++idx ]
    }
  }
});

var Warp = require(__dirname + '/lib/warp')
, warp = new Warp({
    port: opts.p || opts.port || 8800
    , autoCloseClients: opts.c
    , showHeader: opts.h
    , enableClientLog: opts.l
  });

warp.startServer()
